In [1]:
# Importing
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pandas_datareader as pdr

import datetime as dt

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
# Create your connection.
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import sqlite3
cnx = sqlite3.connect('db.sqlite')

In [2]:
df_casos = pd.read_sql('select * from casos_covid_semanal', cnx)

In [12]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation='relu', name='layer1'),
        layers.Dense(3, activation='relu', name='layer2'),
        layers.Dense(4, name='layer3'),
    ]
)
# layer.weights
# # Call model on a test input
x = tf.ones((5, 5))
y = model(x)
# y
# model.weights
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (5, 2)                    12        
                                                                 
 layer2 (Dense)              (5, 3)                    9         
                                                                 
 layer3 (Dense)              (5, 4)                    16        
                                                                 
Total params: 37
Trainable params: 37
Non-trainable params: 0
_________________________________________________________________


In [23]:
tf.ones((2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2))

<tf.Tensor: shape=(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[[[[[[[[[[[[1., 1.],
                     [1., 1.]],

                    [[1., 1.],
                     [1., 1.]]],


                   [[[1., 1.],
                     [1., 1.]],

                    [[1., 1.],
                     [1., 1.]]]],



                  [[[[1., 1.],
                     [1., 1.]],

                    [[1., 1.],
                     [1., 1.]]],


                   [[[1., 1.],
                     [1., 1.]],

                    [[1., 1.],
                     [1., 1.]]]]],




                 [[[[[1., 1.],
                     [1., 1.]],

                    [[1., 1.],
                     [1., 1.]]],


                   [[[1., 1.],
                     [1., 1.]],

                    [[1., 1.],
                     [1., 1.]]]],



                  [[[[1., 1.],
                     [1., 1.]],

                    [[1., 1.],
                     [1., 1

In [5]:
# Call layer on a test input
x = tf.ones((1, 4))
layer = layers.Dense(3)
y = layer(x)
layer.weights

[<tf.Variable 'dense/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.8893354 , -0.3279702 , -0.9108008 ],
        [-0.46813658, -0.7604911 ,  0.15675712],
        [ 0.4313022 , -0.4710094 , -0.41241306],
        [-0.3580662 , -0.57673967,  0.18143892]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [29]:
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))
model.add(layers.Conv2D(32, 5, strides=2, activation='relu'))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.MaxPooling2D(3))

# model.summary()

model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.MaxPooling2D(2))


model.add(layers.GlobalMaxPooling2D())

model.add(layers.Dense(10))
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_26 (Conv2D)          (None, 123, 123, 32)      2432      
                                                                 
 conv2d_27 (Conv2D)          (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d_13 (MaxPoolin  (None, 40, 40, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_28 (Conv2D)          (None, 38, 38, 32)        9248      
                                                                 
 conv2d_29 (Conv2D)          (None, 36, 36, 32)        9248      
                                                                 
 max_pooling2d_14 (MaxPoolin  (None, 12, 12, 32)       0         
 g2D)                                                

In [50]:
from sklearn.datasets import make_regression
make_regression(n_samples=100, n_features=2, noise=0.1, random_state=1)

(array([[ 0.0465673 ,  0.80186103],
        [-2.02220122,  0.31563495],
        [-0.38405435, -0.3224172 ],
        [-1.31228341,  0.35054598],
        [-0.88762896, -0.19183555],
        [-1.61577235, -0.03869551],
        [-2.43483776, -0.31011677],
        [ 2.10025514,  0.19091548],
        [-0.50446586, -1.44411381],
        [ 1.14472371, -1.10061918],
        [ 0.58281521,  0.04221375],
        [ 0.07734007,  0.42349435],
        [ 1.1110567 ,  1.90465871],
        [ 0.61838026,  0.07782113],
        [-0.24863478,  2.52832571],
        [-1.89636092,  2.19069973],
        [-0.77516162, -0.02461696],
        [ 0.5505375 , -1.23005814],
        [-0.85951594,  0.84616065],
        [-0.61736206, -0.11044703],
        [ 0.2135339 ,  0.98633519],
        [-2.3015387 ,  0.86540763],
        [-0.3198016 ,  0.68006984],
        [ 0.40890054,  1.12141771],
        [ 0.13770121,  0.52946532],
        [-0.63873041, -0.37528495],
        [-0.17470316,  0.49521132],
        [-0.87785842, -0.172

In [32]:
# example of making predictions for a regression problem
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import make_regression
from sklearn.preprocessing import MinMaxScaler
# generate regression dataset
X, y = make_regression(n_samples=100, n_features=2, noise=0.1, random_state=1)
scalarX, scalarY = MinMaxScaler(), MinMaxScaler()
scalarX.fit(X)
scalarY.fit(y.reshape(100,1))
X = scalarX.transform(X)
y = scalarY.transform(y.reshape(100,1))
# define and fit the final model
model = Sequential()
model.add(Dense(4, input_shape=(2,), activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='adam')
model.fit(X, y, epochs=1000, verbose=0)
# new instances where we do not know the answer
Xnew, a = make_regression(n_samples=3, n_features=2, noise=0.1, random_state=1)
Xnew = scalarX.transform(Xnew)
# make a prediction
ynew = model.predict(Xnew)
# show the inputs and predicted outputs
for i in range(len(Xnew)):
	print("X=%s, Predicted=%s" % (Xnew[i], ynew[i]))

1/1 [==============================] - 0s 100ms/step
X=[0.29466096 0.30317302], Predicted=[0.17302933]
X=[0.39445118 0.79390858], Predicted=[0.7454226]
X=[0.02884127 0.6208843 ], Predicted=[0.4017805]


In [48]:
scalarX.transform(X)

array([[0.64297807, 0.56183444],
       [0.54613103, 0.53656241],
       [0.62281901, 0.50339909],
       [0.57936502, 0.53837695],
       [0.59924474, 0.51018619],
       [0.56515754, 0.51814578],
       [0.52681392, 0.50403842],
       [0.73911912, 0.53008001],
       [0.61718208, 0.44509793],
       [0.69438701, 0.46295136],
       [0.6680819 , 0.52235111],
       [0.64441866, 0.5421685 ],
       [0.69281092, 0.61915332],
       [0.66974684, 0.52420183],
       [0.62915852, 0.65156896],
       [0.5520221 , 0.63402055],
       [0.60450977, 0.51887752],
       [0.66657086, 0.45622366],
       [0.60056082, 0.56413695],
       [0.61189697, 0.51441643],
       [0.65079442, 0.57142265],
       [0.53305417, 0.56513733],
       [0.62582693, 0.55550424],
       [0.65994028, 0.57844368],
       [0.6472444 , 0.54767644],
       [0.61089664, 0.50065125],
       [0.63261954, 0.54589605],
       [0.59970213, 0.5111949 ],
       [0.6243079 , 0.53575863],
       [0.59615167, 0.55864808],
       [0.